name: Production Readiness

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint and Typecheck
        run: |
          npm run lint:check --if-present
          npm run typecheck --if-present

      - name: Run Tests
        run: npm test -- --ci --reporters=default --reporters=jest-junit
        env:
          JEST_JUNIT_OUTPUT_DIR: ./coverage
          JEST_JUNIT_OUTPUT_NAME: junit.xml

      - name: Production Verification
        run: npm run verify:production --if-present

      # Optional EAS build verification (disabled by default)
      # - name: Setup EAS
      #   run: npm install -g eas-cli
      # - name: EAS Build (Preview)
      #   run: eas build --platform all --profile preview --non-interactive
